apiVersion: v1
kind: Service
metadata:
  name: tarot
  labels:
    app: tarot
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600  # 1시간 WebSocket 연결 유지
  ports:
  - port: 4007
    targetPort: 4007
    protocol: TCP
    name: websocket
  selector:
    app: tarot
