apiVersion: v1
kind: Service
metadata:
  name: concierge
  labels:
    app: concierge
spec:
  type: ClusterIP
  ports:
  - port: 4011
    targetPort: 4011
    protocol: TCP
    name: websocket
  selector:
    app: concierge
