apiVersion: v1
kind: Service
metadata:
  name: blind-date
  labels:
    app: blind-date
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
  - port: 4010
    targetPort: 4010
    protocol: TCP
    name: websocket
  selector:
    app: blind-date
